language: cpp
dist: trusty
sudo: false

compiler:
    - g++

addons:
    apt:
        package:
            - build-essential
            - cmake
            - libboost-all-dev
            - libboost-system1.54.0
            - libboost-chrono1.54.0
            - libboost-random1.54.0
            - libssl-dev

before_install:
    - bash tests/before_install.sh
    - export LIBTORRENT=$PWD/libtorrent-rasterbar/build/
    - export LIBRARY_PATH=$LIBTORRENT/lib/:$LIBRARY_PATH
    - export CPLUS_INCLUDE_PATH=$LIBTORRENT/include/:$CPLUS_INCLUDE_PATH

install:
    - bash tests/install.sh

before_script:
    - bash tests/before_script.sh

script:
    - basg tests/script.sh
